// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// 
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkj5sSSeOv6uPTMb8PgwiCRpFvhiPtfm4',
    appId: '1:974037748639:web:972e49dbe39579318ecbaa',
    messagingSenderId: '974037748639',
    projectId: 'aibay-716ff',
    authDomain: 'aibay-716ff.firebaseapp.com',
    storageBucket: 'aibay-716ff.firebasestorage.app',
    measurementId: 'G-GQTTSJ8Q2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGlgzK0N9wn0-Ulp1CRhlK_RwYUYu2Otg',
    appId: '1:974037748639:android:4ac22492f9bb1ded8ecbaa',
    messagingSenderId: '974037748639',
    projectId: 'aibay-716ff',
    storageBucket: 'aibay-716ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSgcvFDwRN8ZXMhKbBTZwK1KJrnJ_eh2g',
    appId: '1:974037748639:ios:0e23f162f90cfc0b8ecbaa',
    messagingSenderId: '974037748639',
    projectId: 'aibay-716ff',
    storageBucket: 'aibay-716ff.firebasestorage.app',
    iosBundleId: 'com.example.aibay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSgcvFDwRN8ZXMhKbBTZwK1KJrnJ_eh2g',
    appId: '1:974037748639:ios:0e23f162f90cfc0b8ecbaa',
    messagingSenderId: '974037748639',
    projectId: 'aibay-716ff',
    storageBucket: 'aibay-716ff.firebasestorage.app',
    iosBundleId: 'com.example.aibay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkj5sSSeOv6uPTMb8PgwiCRpFvhiPtfm4',
    appId: '1:974037748639:web:16b571746ea2fd2a8ecbaa',
    messagingSenderId: '974037748639',
    projectId: 'aibay-716ff',
    authDomain: 'aibay-716ff.firebaseapp.com',
    storageBucket: 'aibay-716ff.firebasestorage.app',
    measurementId: 'G-VXVJRN19Z9',
  );
}